name: create geojson

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  update_data:
    defaults:
      run:
        working-directory: script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: install python
        working-directory: script
        run: uv python install

      - name: install dependencies
        working-directory: script
        run: uv sync --locked

      - name: generate data
        working-directory: script
        run: |
          ./generate.sh
          for f in *.json; do
              mv "$f" ../static/
          done

      - name: get current year, month for branch name
        id: date
        run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      - uses: peter-evans/create-pull-request@v8
        with:
          commit-message: 'chore: updated geojson files (${{ steps.date.outputs.date }})'
          title: 'update ${{ steps.date.outputs.date }}'
          branch: 'feat/${{ steps.date.outputs.date }}-update'
          add-paths: |
            static/*.json
